#!/bin/sh

APPDIR=$(dirname "$0")
java  -Djava.library.path="$APPDIR:$APPDIR/lib" -cp "$APPDIR/lib/Wii_BP0_8.jar:$APPDIR/lib/core.jar:$APPDIR/lib/jogl-all.jar:$APPDIR/lib/gluegen-rt.jar:$APPDIR/lib/jogl-all-natives-linux-amd64.jar:$APPDIR/lib/gluegen-rt-natives-linux-amd64.jar:$APPDIR/lib/OBJLoader.jar:$APPDIR/lib/controlP5.jar:$APPDIR/lib/RXTXcomm.jar:$APPDIR/lib/serial.jar" Wii_BP0_8 "$@"
